/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Alumno;
import entidades.Materia;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.AlumnoData;
import modelo.Conexion;
import modelo.MateriaData;
import static vistas.vistaUniversidad.jdpEscritorio;

/**
 *
 * @author Jesus Lucero
 */
class CustomTableModel2 extends DefaultTableModel {

    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
}

public class vistaMateriaBuscar extends javax.swing.JInternalFrame {

    private CustomTableModel2 tablaMaterias;
    private ArrayList<Materia> listaMaterias;
    private ArrayList<Object> columnas;
    private Conexion c = new Conexion();

    public vistaMateriaBuscar() {
        initComponents();
        tablaMaterias = new CustomTableModel2();
        columnas = new ArrayList<>();
        cabeceraTabla();
        jtMaterias.setModel(tablaMaterias);
        modificarVisible(false);
        
        
    }
    public void modificarVisible(boolean variable){
        jlId.setEnabled(variable);
        jlNombre.setEnabled(variable);
        jtfId.setEnabled(variable);
        jtfNombre.setEnabled(variable);
        jbtnGuardar.setEnabled(variable);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgListar = new javax.swing.ButtonGroup();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jProgressBar1 = new javax.swing.JProgressBar();
        jtfIdAlumno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();
        jbtnModificar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnBuscar = new javax.swing.JButton();
        jrbListarPorId = new javax.swing.JRadioButton();
        jrbListarTodos = new javax.swing.JRadioButton();
        jlNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfId = new javax.swing.JTextField();
        jlId = new javax.swing.JLabel();
        jbtnGuardar = new javax.swing.JButton();

        setTitle("Buscar Alumno");

        jtfIdAlumno.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfIdAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdAlumnoActionPerformed(evt);
            }
        });
        jtfIdAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfIdAlumnoKeyTyped(evt);
            }
        });

        jtMaterias.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtMaterias);

        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnBuscar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        bgListar.add(jrbListarPorId);
        jrbListarPorId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jrbListarPorId.setText("Listar materia por id");
        jrbListarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbListarPorIdActionPerformed(evt);
            }
        });

        bgListar.add(jrbListarTodos);
        jrbListarTodos.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jrbListarTodos.setText("Listar todas las materias");
        jrbListarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbListarTodosActionPerformed(evt);
            }
        });

        jlNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlNombre.setText("Nombre:");

        jtfNombre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jtfId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jlId.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jlId.setText("ID:");

        jbtnGuardar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbListarTodos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbListarPorId)
                                .addGap(38, 38, 38)
                                .addComponent(jtfIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNombre)
                    .addComponent(jlId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jbtnGuardar))
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnModificar)
                .addGap(18, 18, 18)
                .addComponent(jbtnEliminar)
                .addGap(18, 18, 18)
                .addComponent(jbtnCancelar)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jrbListarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbListarPorId)
                    .addComponent(jbtnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jbtnGuardar)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnModificar)
                    .addComponent(jbtnEliminar)
                    .addComponent(jbtnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIdAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdAlumnoActionPerformed

    private void jrbListarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbListarTodosActionPerformed
        jtfIdAlumno.setEnabled(false);
    }//GEN-LAST:event_jrbListarTodosActionPerformed

    private void jrbListarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbListarPorIdActionPerformed
        jtfIdAlumno.setEnabled(true);
    }//GEN-LAST:event_jrbListarPorIdActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        if (jrbListarTodos.isSelected()) {
            limpiarTabla();
            listarTodos();
        }
        else if (jrbListarPorId.isSelected()){
            limpiarTabla();
            listarPorId();
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
                modificarVisible(true);
                                
                String id =  String.valueOf(tablaMaterias.getValueAt(jtMaterias.getSelectedRow(),0));
                String nombre = String.valueOf(tablaMaterias.getValueAt(jtMaterias.getSelectedRow(),1));
                          
                jtfId.setText(id);
                jtfNombre.setText(nombre);
               
                 

    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        if (jtMaterias.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UNA MATERIA");
        }
        else if (JOptionPane.showInternalConfirmDialog(this, "¿Esta seguro que desea eliminar la materia?") == 0){
        MateriaData md = new MateriaData(c);
        md.quitarMateria((int)tablaMaterias.getValueAt(jtMaterias.getSelectedRow(), 0));
        JOptionPane.showMessageDialog(this, "Materia Borrada");
        jbtnBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jtfIdAlumnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfIdAlumnoKeyTyped
        
       
    }//GEN-LAST:event_jtfIdAlumnoKeyTyped

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        MateriaData md = new MateriaData(c);
        Materia materia = new Materia();
            
        materia.setIdMateria(Integer.parseInt(jtfId.getText()) );
        materia.setNombreMateria(jtfNombre.getText());
        md.modificarMateria(materia,materia.getIdMateria(),materia.getNombreMateria());
        JOptionPane.showMessageDialog(this, "Materia Actualizada con exito");
        jbtnBuscarActionPerformed(null);
    }//GEN-LAST:event_jbtnGuardarActionPerformed
    
    
    public void listarPorId(){
        AlumnoData alumnoData = new AlumnoData(c);
        Alumno alumno = alumnoData.buscarAlumno(Integer.parseInt(jtfIdAlumno.getText()));
        String activo;
        if (alumno.isActivo()) {
            activo = "si";
        } else {
            activo = "no";
        }
        tablaAlumnos.addRow(new Object[]{alumno.getId_alumno(), alumno.getNombre_alumno(), alumno.getFn_alumno(), activo});
      
      }
    
    public void listarTodos() {
        AlumnoData alumnoData = new AlumnoData(c);
        listaAlumnos = alumnoData.buscarAlumnos();

        for (Alumno it : listaAlumnos) {
            String activo;
            if (it.isActivo()) {
                activo = "si";
            } else {
                activo = "no";
            }
            tablaAlumnos.addRow(new Object[]{it.getId_alumno(), it.getNombre_alumno(), it.getFn_alumno(), activo});
        }

    }

    public void limpiarTabla() {
        int x = tablaAlumnos.getRowCount() - 1;
        for (int it = x; it >= 0; it--) {
            tablaAlumnos.removeRow(it);
        }

    }

    public void cabeceraTabla() {
        columnas.add("ID");
        columnas.add("NOMBRE");
        columnas.add("FECHA DE NACIMIENTO");
        columnas.add("ACTIVO");

        for (Object it : columnas) {
            tablaAlumnos.addColumn(it);
        }
        jtMaterias.setModel(tablaAlumnos);
        jtMaterias.getTableHeader().setReorderingAllowed(false);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgListar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JRadioButton jrbListarPorId;
    private javax.swing.JRadioButton jrbListarTodos;
    private javax.swing.JTable jtMaterias;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfIdAlumno;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
